# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'calendar_final' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for calendar_final
  pod 'FSCalendar'
  pod 'UITextView+Placeholder'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'RealmSwift'
end
